### ISSUE TITLE
Superfluous Output

### ISSUE THREAD

**Issue by Naatan** [photostorm/pty#2]
I've been trying to figure out why the windows implementation has a tendency to produce superfluous output. It seems to often start with the path of the executable, followed by an ALERT signal (unicode U+0007). It seems to do this almost every single invocation, but depending on the performance of the host as well as the process being ran it may be cut off differently, and may even appear intermixed with regular output.

I've created a repro of the issue here:

https://github.com/ActiveState/termtest/blob/a695852f3f6479d5fbed93abd19562525c4045cf/test/pty/pty_test.go

Note this repro itself has a bug which I haven't bothered to further debug at this time as it is a red herring. But basically it will never exit, as the last read just hangs. I'm not getting this with our regular use of the lib so won't bother digging on that.

Anyway, if you run this test you will get something like this (again: host and process performance may affect this):

```
Read: 








]0;C:\Program Files\Go\bin\go.exeRead: hello
```

The first read seems entirely superfluous, though note it's not guaranteed to happen in the first read, or even at all.

It seems there is some sort of race condition happening somewhere, but so far I've been unable to nail it down.

**Comment by photostorm** [comment]
I only see it happen when you run it in a unit test

**Comment by Naatan** [comment]
It may be packaged in a test file but the code as written is not mocking or skipping any logic. Regardless, a test is meant to verify code is working as expected, and in this case this test is raising that the code  is not working as expected. Are you saying this isn't a bug?

**Comment by photostorm** [comment]
I not saying whether or not it is a bug, just pointing out that I am only see it in testing environment. I try to look into it more.

**Comment by Naatan** [comment]
Gotcha. Interesting that you're not seeing this outside a testing environment.. I'm seeing it both on slow CI machines as well as on my fast local machine. Both on Windows 10 and 11. While there is an element of randomness to exactly what part of the executable path it will print, there's always something it seems.

I've also noticed in some tests that if I run it against a cmd.exe, and then run other commands from within that cmd.exe, it again seems to repeat the path of the executable being ran. I can see if I can reproduce this in a more focused test if it's helpful.

**Comment by Naatan** [comment]
I realized after researching this some more that these are window title escape sequences:

https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#window-title

Which is perfectly fine for the pty to communicate. Unfortunately, I don't believe a windows console emulator exists in Golang (if it does; please share!), so if anyone else is running into this, I've written some crude code to filter most of the escape sequences out:

https://github.com/ActiveState/termtest/commit/654262681ae33101b649ebfcc547766a0d1221b8

Not a perfect solution by any means, but for now it serves its purpose. Hopefully some day we'll see a windows console emulator, cause I don't think it's going anywhere unfortunately.

Anyway, definitely not a bug with this lib.. sorry for the distraction @photostorm.
